<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Slim 3 App Skeleton">
    <meta name="author" content="Vitalii Lupu">
    <title>Slim 2</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css">
    <!-- Custom styles for this template -->
    <link href="css/styles.css?v=2" rel="stylesheet">
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.2/html5shiv.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/respond.js/1.2.0/respond.js"></script>
    <![endif]-->
</head>
<body>
<main class="container">
    <div class="col-lg-12 text-center">
        <div class="jumbotron">
            <h1 class="slim-title">Slim 3</h1>
            <p class="lead">a micro framework for PHP</p>
        </div>
		<?php if ( isset( $name ) ) : ?>
            <h2>Hello <?= htmlspecialchars( $name ); ?>!</h2>
		<?php else: ?>
            <p>Try <a href="http://www.slimframework.com">SlimFramework</a></p>
		<?php endif; ?>
        <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
        <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
    </div>
</main>
</body>
</html>